[package]
name = "rust-profiling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#jemalloc-sys = "0.5.3+5.3.0-patched"
#jemallocator = "0.5.0"
#jemalloc-ctl = "0.5.0"
alloc_counter = "0.0.4"